version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: ${CONTAINER_NAME}
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      ServerIP: ${SERVER_IP}
      TZ: ${TIME_ZONE}
      WEBPASSWORD: ${WEB_PASSWORD} 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
       - "${DOCKER_CONFIGS}/etc/pihole/:/etc/pihole/"
       - "${DOCKER_CONFIGS}/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities    
    cap_add:
      - NET_ADMIN 

